Resources:
  #the federated identity for out user pool to auth with
  CognitoIdentityPool:
    Type: AWS::Cognitio::IdentityPool
    Properties:
      #Generate a name based on the stage
      IdentityPoolName: ${self:custom.stage}IdentityPool
      #Dont allow unathenticated users
      AllowUnathenticatedIdentities: false
      #Link to our User Pool.
      CognitioIdentityProviders:
       - ClientId:
           Ref: CognitoUserPoolClient
         ProviderName:
           Fn::GetAtt: ["CognitoUserPool","ProviderName"]

#IAM ROLES
CognitoIdentityPoolRoles:
  Type: AWS::Cognito::IdentityPoolRoleAttachement
  Properties:
    IdentityPoolId:
      Ref: CognitioIdentityPool
    Roles:
      authenticated:
        Fn::GetAtt: [CognitoAuthRole, Arn]

#Iam role used for authed users
CognitoAuthRole:
  Type: AWS::IAM::Role
  Properties:
    Path: /
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement: 
        - Effect: 'Allow'
          Principal: 
            Federated: 'cognito-identity.amazonaws.com'
          Action:
            - 'sts:AssumeRoleWithWebIdentity'
          Condition:
            StringEquals:
              'cognito-identity.amazonaws.com:aud'
                Ref: CognitoIdentityPool
            'ForAnyValue:StringLike':
              'cognito-identity.amazonaws.com:amr': authenticated
Polices:
  - PolicyName: 'CognitoAuthorizedPolicy'
    PolicyDocument: 
      Version: '2012-10-17'
      Statement: 
        - Effect: 'Allow'
          Action:
            - 'mobileanalytics:PutEvents'
            - 'cognito-sync:*'
            - 'cognito-identity:*'
          Resource: '*'

        #Allow users to invoke our API
        - Effect: 'Allow'
          Action:
            - 'execute-api:Invoke'
          Resources:
            Fn::Join:
              - ''
              -
                - 'arn:aws:execute-api'
                - Ref: AWS::Region
                - ':'
                - Ref: AWS::AccountId
                - ':'
                - Ref: ApiGatewayRestApi
                - '/*'
          
          #Allow users to upload attachments to their 
          #folder inside our S3 Bucket
        - Effect: 'Allow'
          Action:
            - 's3:*'
          Resource:
            - Fn::Join:
              - ''
              -
                - Fn::GetAtt: [AttachmentsBucket, Arn]
                - '/private/'
                - '$'
                - '{cognito-identity.amazonaws.com:sub}/*'

##Print out the Id od the identity pool that was created
Outputs:
  IdentityPoolId:
    Value:
      Ref: CognitoIdentityPool
      
